a=input("Enter the first number")
c=int(a)
b=input("Enter the second number")
d=int(b)
print("Addition:",c+d)
print("Difference:",c-d)
print("Multiplication:",c*d)
print("Division:",c/d)
print("Integer Division:",c//d)
print("Power:",c**d)
